### ISSUE TITLE
Object::Config is not defined in MRI 2.2.0

### ISSUE THREAD

**Issue by jnv** [interagent/pliny#111]
config_helpers file [attempts to remove](https://github.com/interagent/pliny/blob/8a4cd6220e8e96849ed09a7b8410ec333c55e879/lib/pliny/config_helpers.rb#L86) the `Config` constant due to a deprecation warning in earlier versions of MRI. In MRI 2.2.0 the constant is finally removed, but this breaks Pliny under 2.2.0 with NameError (constant Object::Config not defined).

The line should check whether the constant is actually defined on `Object` and only then remove it, e.g.:

``` ruby
Object.send :remove_const, :Config if Object.const_defined? :Config
```

**Comment by brandur** [comment]
Nice catch and fix guys! Thanks.

**Comment by neilmiddleton** [comment]
Can we post a release so I can use this on 2.2.0?  It doesn't appear that this is in the latest tag.

**Comment by brandur** [comment]
@neilmiddleton Yep! Pushed 0.6.0. Let us know if you run into any other issues.

/cc @will
