### ISSUE TITLE
Incongruous RSpec expectation config

### ISSUE THREAD

**Issue by yesmeck** [interagent/pliny#132]
Rspec expectation is configured to minitest in this line https://github.com/interagent/pliny/blob/master/lib%2Ftemplate%2Fspec%2Fspec_helper.rb#L39, but the spec template still using RSpec syntax.

**Comment by brandur** [comment]
@yesmeck Excellent point. This should be fixed by #133, but let me know if you find anymore instances of it. Thanks!
