### ISSUE TITLE
Filter incoming params

### ISSUE THREAD

**Issue by dmathieu** [interagent/pliny#164]
We currently don't have any way of filtering incoming parameters, which ends up in several apps not doing so at all, and a potential for security issues.
This issue is here to discuss a parameters filtering middleware that would allow solving that problem.

My idea -heavily inspired by how [rails' StrongParameters](http://api.rubyonrails.org/classes/ActionController/StrongParameters.html) works would be to have the middleware entirely replace the `params` object to be a `Pliny::FilteredParams`.
That object would behave like a hash, but wouldn't return any non-allowed keys.

eg:

```
Pliny::FilteredParams.new({hello: 'world'}).keys #=> []
Pliny::FilteredParams.new({hello: 'world'}).allow!(:hello).keys #=> [:hello]
```

Subhashes would have to be handled properly too.

```
params = Pliny::FilteredParams.new({hello: {bonjour: 'monde'}})
params[:hello].class #=> Pliny::FilteredParams
```

What do you think of this proposal? Any better ideas/objections?

**Comment by pedro** [comment]
Hey Damien!

I totally see the case for this, but I think StrongParameters provides a subset of what you'd get with JSON Schema: while it allows you to define which params are required and which are allowed, JSON Schema will go further and also allow you to define param types, examples, documentation, etc.

So do you think there's a case for both existing, or do we just need to provide better examples/tooling to make sure JSON Schema fills this gap?

Thanks,

**Comment by dmathieu** [comment]
https://github.com/fge/json-schema-validator/wiki/v5:-strictProperties

**Comment by neilmiddleton** [comment]
> I think StrongParameters provides a subset of what you'd get with JSON Schema

Would pliny be able to enforce the params outlined in JSON schema though?

**Comment by pedro** [comment]
That's where [committee](https://github.com/interagent/committee) comes in!
We should add it to the template so it's clear how to integrate, but it's as simple as adding a middleware.

**Comment by brandur** [comment]
+1 guys. Who knows if it's the right thing, but the basic idea here is that Committee will use your schema to perform strong parameter validation before the request ever hits one of your endpoints, allowing you to be very optimistic that everything is well-formed.
