### ISSUE TITLE
rake db:rollback not working

### ISSUE THREAD

**Issue by rhyselsmore** [interagent/pliny#167]
Appears to be a regression in the latest version (0.8) when running rake db:rollback. 

The migration doesn't actually run for some reason.

I'm trying to get to the bottom of why.

**Comment by pedro** [comment]
Talked to @rhyselsmore – I ran into this recently too, just didn't send a patch before because I was having trouble to write tests. Anyways, should be fixed in #168 – in the meantime db:reset will do.

**Comment by rhyselsmore** [comment]
:dancers: :+1:
