### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by duduribeiro** [interagent/pliny#180]
Is it the plan of pliny to allow the use of mongodb as optional resource?
If so, I'm changing some items to use on my current project and open a PR for it.

Thanks so much. :beers:

**Comment by pedro** [comment]
Oi Kadu :}

We unfortunately don't have plans to support Mongo (nor other relational databases fwiw). Pliny is more like the embodiment of our favorite practices and approaches to writing an API than a regular framework that supports a range of technologies. Knowing exactly what is the data store and how it behaves allows us to make some conveniently blunt calls on how to use and operate it.

That said I'd still love to see the diff you have to support Mongo! I have no idea at this point, but maybe there is a compromise we can take to keep moving in this direction but still allow people to exchange some parts when they want.

I'm closing for now but ping us here if you can share a branch!
