### ISSUE TITLE
Thor required arguments don't seem to be required.

### ISSUE THREAD

**Issue by mathias** [interagent/pliny#189]
```
$ pliny-generate serializer
created serializer file ./lib/serializers/.rb
created test ./spec/serializers/_spec.rb
```

These commands are Thor actions, which indicates that the name should be required at the Thor level: https://github.com/erikhuda/thor/wiki/Getting-Started#task-parameters

I'm hesitant to add logic here if Thor is supposed to fail the task for us. Thoughts? Could it be because we're not inheriting from Thor correctly? Looking at the Thor docs, it seems correct, but we aren't taking advantage of `Thor::Actions` in the generators class. Doesn't seem like we need it, though.

**Comment by pedro** [comment]
AH! It's because of the method signature.

See https://github.com/interagent/pliny/pull/190
