### ISSUE TITLE
seed.rb comment is misleading

### ISSUE THREAD

**Issue by cyberdelia** [interagent/pliny#194]
A Sequel database connection can be obtained via Sequel::Model.db

If you're running ``rake db:seeds`` against multiple database, ``Sequel::Model.db`` will point to the first database it connect to, resulting in running SQL against the same database against. A workaround is to use ``db = Sequel::DATABASES.last``.

**Comment by brandur** [comment]
Added a fix for the comment in b4132a3.

This is a great find though; we'd never intended it to be so janky. I wonder if we should switch to some kind of method-based model. For example:

``` ruby
# db/seeds.rb
module DB::Seeds
  def seed(db)
    ...
  end
end
```

``` ruby
# lib/pliny/tasks/db.rake
require "db/seeds"
database_urls.each do |database_url|
  db = Sequel.connect(database_url)
  DB::Seeds.seed(db)
end
```

Thoughts @cyberdelia?

**Comment by cyberdelia** [comment]
Looks more sane, since the last alternative is to expose some sort of global var.

**Comment by pedro** [comment]
Great find!

I'm in favor of a global var for this kind of thing. How would you guys feel if seeds just had a `DB` constant available to it?

I think in general that file is optimized for readability and conciseness, so I wouldn't even go with the module/method approach seeing that it doesn't answer the question of how does that method get called/receive a db instance in first place.

**Comment by cyberdelia** [comment]
@pedro That would still be better than ``Sequel::DATABASES.last`` so :+1:

**Comment by gudmundur** [comment]
Closing this issue since I'm assuming https://github.com/interagent/pliny/pull/223 has properly addressed this.
