### ISSUE TITLE
Running migrations before running tests

### ISSUE THREAD

**Issue by cyberdelia** [interagent/pliny#197]
It would be lovely if [before running the tests](https://github.com/interagent/pliny/blob/master/spec/spec_helper.rb#L20), the `spec_helper` would ensure all migrations have been ran against the test database. It's a nice way to ensure tests run against the latest schema.

**Comment by DyegoCosta** [comment]
@cyberdelia did you mean to add it to the [template spec_helper](https://github.com/interagent/pliny/blob/master/lib/template/spec/spec_helper.rb#L36)? I think it's a good idea as well, I can add that check

I believe we have two options here, use the Sequel default error message

```ruby
Sequel::Migrator.check_current(DB, "#{Config.root}/db/migrate")
````
```
$ rake                                                                      [ruby-2.2.1]
rake aborted!
Sequel::Migrator::NotCurrentError: migrator is not current
/Users/dyego/.rvm/gems/ruby-2.2.1/gems/sequel-4.24.0/lib/sequel/extensions/migration.rb:368:in `check_current'
/Users/dyego/code/magenta/spec/spec_helper.rb:11:in `<top (required)>'
/Users/dyego/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `require'
...
Tasks: TOP => default => spec
(See full trace by running task with --trace)
```

Or check if it's current and fail with our own error message

```ruby
unless Sequel::Migrator.if_current(DB, "#{Config.root}/db/migrate")
  fail "Our own error message"
end
```

Do you think we need a custom message or Sequel's default is fine?

**Comment by cyberdelia** [comment]
I would rather have the migration applied rather than just a check, but that could be a could be a good first step.

**Comment by gudmundur** [comment]
I like the idea, yet I'm reluctant to running the migrations automatically. If we do, then what should we do with the `-development` database? Often you'll also want your tests to pass, even though you haven't migrated the database. The example I'm thinking here is where you have deployed things, but migrations haven't run yet.

**Comment by cyberdelia** [comment]
The main goal would be to avoid running tests against an outdated schema. What we currently do is:

```ruby
begin
  require "sequel/extensions/migration"
  Sequel::Migrator.check_current(Sequel::Model.db, 'db/migrate')
rescue Sequel::Migrator::Error
  abort("Test database is not up-to-date, please run: bundle exec rake db:setup")
end
```
