### ISSUE TITLE
Migration wiki page

### ISSUE THREAD

**Issue by DyegoCosta** [interagent/pliny#198]
___Can we use the text bellow for the [Migration wiki page](https://github.com/interagent/pliny/wiki/Migrations)? Any suggestion to improve it?___

You can use use the [migration generator](https://github.com/interagent/pliny/blob/master/lib/pliny/commands/generator/migration.rb) to create a new Sequel migration to modify your database schema.

Create a new migration like:

```
$ pliny-generate migration "add phone to artists"
created migration ./db/migrate/1438776880_add_phone_to_artists.rb
```

It will create an empty migration:

```ruby
Sequel.migration do
  up do
  end

  down do
  end
end
```

You can edit the migration to suit your needs and then run it with:

```
$ rake db:migrate
```

Further reading:

- [Sequel Migrations](http://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html)
- [Sequel Schema modification methods](http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html)

**Comment by pedro** [comment]
YES! This looks like a really solid start to me :+1:

Can you create the wiki page yourself? I checked the settings and it should be public, so feel free to go for it!

Thanks,

**Comment by DyegoCosta** [comment]
@pedro :+1: https://github.com/interagent/pliny/wiki/Migrations
