### ISSUE TITLE
Volunteering to help out with Pliny

### ISSUE THREAD

**Issue by gudmundur** [interagent/pliny#231]
Hi @pedro, @brandur and others that are contributors to Pliny.

I'm hereby offering my help in maintaining Pliny and being one of the go to people within Heroku for all things Pliny.

Thanks,
Guðmundur Bjarni

**Comment by dmathieu** [comment]
:+1:

**Comment by ys** [comment]
GUDMUNDUR PRESIDENT

**Comment by dmathieu** [comment]
![](http://cdn.meme.am/instances/500x/65716438.jpg)

**Comment by brandur** [comment]
@gudmundur Amazing! Thank-you :)

I'm still a big fan of the ideas behind this project, but am a little frustrated by how little time that I've been able to apply to it recently.

I just talked this over with Pedro and have added you to the contributors list.

**Comment by gudmundur** [comment]
Yay! Thanks guys.

**Comment by pedro** [comment]
+999 welcome!
