### ISSUE TITLE
RFC: Add app_name and source to default config

### ISSUE THREAD

**Issue by gudmundur** [interagent/pliny#233]
For most pliny apps I've created, I've added `Config.app_name` and `Config.source` to track the app and environment. This is useful for setting up a default log context and measuring values.

With those two config values, we can add them as defaults to [`config/initializers/log.rb`](https://github.com/interagent/pliny/blob/6c8c968cff894607a637be1e4187f55538dc6b2d/lib/template/config/initializers/log.rb).

**Comment by pedro** [comment]
+1 for app! We can infer from `pliny-new` and set that for new pliny apps.
What is `source`, the process name?

**Comment by gudmundur** [comment]
@pedro `source` is the stage it's running in, i.e. `development`, `staging` or `production`.

**Comment by pedro** [comment]
ooo Pliny already has it – we call it `deployment` (though it needs better documentation as everything else)

**Comment by dpiddy** [comment]
Closed by https://github.com/interagent/pliny/pull/240 and https://github.com/interagent/pliny/pull/243?

**Comment by brandur** [comment]
@dpiddy Good call! Thank-you :)

**Comment by gudmundur** [comment]
Thanks, I had forgotten about this issue.
