### ISSUE TITLE
The PLINY_ENV default bubbles to RACK_ENV

### ISSUE THREAD

**Issue by gudmundur** [interagent/pliny#237]
If `PLINY_ENV` is left unset on staging or production environments, it causes Puma to override `RACK_ENV` to `development`, [see here](https://github.com/puma/puma/blob/e81a1326ea7a791d7729b7674b5bebf9409657aa/lib/rack/handler/puma.rb#L21-L23).

What is the motivation behind `PLINY_ENV` and how should it differ from `RACK_ENV`? Should it its default be equal to `ENV['RACK_ENV']`?

**Comment by dmathieu** [comment]
PLINY_ENV was discussed and introduced in #138

**Comment by gudmundur** [comment]
@dmathieu Thanks for digging this up.

**Comment by dmathieu** [comment]
I believe this can be closed.

**Comment by gudmundur** [comment]
@dmathieu thanks for pointing that out.
