### ISSUE TITLE
update PRMD dependency

### ISSUE THREAD

**Issue by heavysixer** [interagent/pliny#248]
Would it be possible to have the Pliny gem use a more current version of PRMD? Right now we are bound to 7, but PRMD is at 11+ now.

**Comment by selectport** [comment]
FWIW, in a modified fork, i simply bumped the gemspec dependency to : 

spec.add_dependency "prmd",  "~> 0.11", ">= 0.11.4"

and while far from exhaustive in my new project, i've not hit any issues with that version of prmd yet.

**Comment by gudmundur** [comment]
Yeah, excellent point. Would you mind opening up a PR for it? I'll get it reviewed and merged in the next couple of days.

@geemus Any objections?

**Comment by selectport** [comment]
Not sure if that was for me or @heavysixer, but since i had it available - PR submitted.

**Comment by heavysixer** [comment]
Thanks @selectport and @gudmundur !

**Comment by geemus** [comment]
Definitely, will merge now.

**Comment by gudmundur** [comment]
Thanks for reporting @heavysixer and thanks for submitting a PR @selectport!

**Comment by heavysixer** [comment]
Awesome, do you know when this will be pushed to a release of Pliny? I am wondering when I can use it in the wild.

**Comment by gudmundur** [comment]
@heavysixer woops, we missed releasing the gem. I've released `0.15.1` now.
