### ISSUE TITLE
Default Rollbar reporting approach is unsafe

### ISSUE THREAD

**Issue by rwz** [interagent/pliny#249]
By default Pliny uses Rollbar's Sinatra middleware that reports all the things, including cookies and HTTP headers (including authorization).

That doesn't seem to be very safe from a security standpoint since it makes it very easy to leak credentials this way. I believe pliny should have a configurable Rollbar context where developer has control over what is included into reported error metadata, instead of including all the things by default.

An example of this approach could be found in heroku/identity app: https://github.com/heroku/identity/blob/c6ced1df12826b8dfd5fc970455bcaa5b0600f1b/lib/identity/error_handling.rb#L47-L56

**Comment by rwz** [comment]
It could probably be a pre-generated middleware that does the reporting and encourages the end-user to modify it as necessary.

**Comment by brandur** [comment]
@rwz: I think that Rollbar scrubs a pretty good collection of fields by default (which will probably be good enough for most users):

https://github.com/rollbar/rollbar-gem#data-sanitization-scrubbing

You can also configure more in there as shown. Should be easy to drop that configuration into an initializer file.

**Comment by rwz** [comment]
@brandur good point, it might be good enough for most users. Although I'd personally definitely prefer a whitelist approach to blacklisting/scrubbing.
