### ISSUE TITLE
Access to log context

### ISSUE THREAD

**Issue by flacoste** [interagent/pliny#5]
Would be nice if the Pliny log helper offered an easy way to add context to the log. It can be done indirectly by stashing variables in the RequestStore, but making the log_context method not private would be a step up.

An alternative might be to offer a context method like the one in scrolls which define block context.

**Comment by pedro** [comment]
Oops, sorry we dropped the ball here, @flacoste!

But happy to say these improvements are in:
https://github.com/interagent/pliny/wiki/Logging#default-log-attributes

Thanks,
