### ISSUE TITLE
Pliny exceptions getting logged to Rollbar

### ISSUE THREAD

**Issue by pedro** [interagent/pliny#92]
Rollbar is injecting its Rack::Builder middleware in a way that it's getting precedence over `Pliny::Middleware::RescueErrors`. This means that internal Pliny exceptions like `Unauthorized` are getting logged before we rescue and convert them into a proper http response.

**Comment by kennyp** [comment]
@pedro Looks like they merged your PR. What do we need to change to get this issue closed?

**Comment by pedro** [comment]
Nothing :} @brandur nailed this down on 1dba7342329ab084e8d742dce6d3decebf3911dc, happy to report I couldn't reproduce the original issue on a new Pliny app.

Thanks!
